### PR TITLE
move bot error channel config to env file

### LINKED ISSUE #283: Allow error channel to be set in `.env` file
## Purpose
What will this feature provide?

Make the `unhandledRejectionHandler` more flexible by defining the the name of the desired error channel in the `.env` file.

### Is your feature request related to a problem? Please describe.
Right now, the error channel is hard-coded to "audit-logs". This is not flexible.

## Proposed Solution
If you have an idea on how to implement this feature, please share!
Set the name as an env variable in `.env` and use that for the channel name!

## Acceptance Criteria
Please list the requirements the implementation of this feature should meet.
- [ ] setting channel name in `.env` should work as long as there is an existing channel with that name in the server.

## Additional context
Initially discussed here:
https://discord.com/channels/810930683732033597/810930684171780117/947589806567866548

### PR DESCRIPTION
**Pull request by mikejoh12**
## What issue is this solving?

Closes #283 

### Description
Moves setting of the channel for bot errors to the .env file.

## Any helpful knowledge/context for the reviewer?
Set the channel in the .env file with the variable BOT_ERROR_CHANNEL_ID. You can add the line below to the .env file:
BOT_ERROR_CHANNEL_ID=ID_FOR_audit-logs

- Is a re-seeding of the database necessary? No
- Any new dependencies to install? No
- Any special requirements to test? No
  - (e.g., admin perms, alt account, etc.)

### Please make sure you've attempted to meet the following coding standards
- [X] Code has been tested and does not produce errors
- [X] Code is readable and formatted
- [X] There isn't any unnecessary commented-out code

### CODE REVIEW

**Comment by aedwardg** [comment]
Not sure if this is a viable option. This is what I tried earlier and had issues with the bot being in multiple servers sharing the same named channel. It posted the errors in the wrong one. 

See
https://discord.com/channels/810930683732033597/810977155130458145/947623394990497883

And
https://discord.com/channels/810930683732033597/810977155130458145/947629493760172113

**Comment by mikejoh12** [comment]
I modified this to use the error channel ID which now has to be set in the .env file. That should work across servers. Solution found in this discord.js bot: https://github.com/Simpleboy353/REAPER-2.0

**Review by lyallstewart — APPROVED** [review]
LGTM!

**Review by aedwardg — APPROVED** [review]
This should work nicely 🚀

**Pull request merged**
