### PR TITLE
Add pre commit hook

### PR DESCRIPTION
**Pull request by aedwardg**
## What issue is this solving?

Closes issue #29 
This PR looks scarier than it is.  Most of the changes are just the result of Prettier's auto-formatting.

### Description

- Configures Prettier for code formatting
- Configures ESLint for Linting
- Adds a pre-commit hook to automatically format and lint all staged files upon `git commit`
- Formats and fixes all linting errors in existing codebase

**NOTE: after this PR is merged, all contributors will need to do a `git pull` on the development branch, followed by an `npm install`**

It might also be worth taking a look at the [Advanced Setup](https://github.com/CodecademyCommunity/codecademy-discord-bot/wiki/Advanced-Setup) instructions I wrote up, for those who want to set up their editors or even just understand what the pre-commit hook does.

@Vic-ST, the Github Actions pipeline should probably be updated to use the command `npm install --production` so that it doesn't have to install the dev-only dependencies on the droplet.  Not a big deal, but it will save a little bit of time and space.

## Any helpful knowledge/context for the reviewer?

- Is a re-seeding of the database necessary? NO
- Any new dependencies to install? YES
- Any special requirements to test? 

To test the pre-commit hook make a new branch off of this one, do `npm install` and then make a new js file with javascript in it. Add and commit it and see what happens.

Not special requirements, _per se_, but all commands should probably be tested out to double check before making this code live. I didn't find any problems with it, but with this amount of change it can't hurt to double check.

### Please make sure you've attempted to meet the following coding standards
- [x] Code has been tested and does not produce errors
- [x] Code is readable and formatted
- [x] There isn't any unnecessary commented-out code

### CODE REVIEW

**Review by fedGL — APPROVED** [review]
This PR touches almost (if not all) files in this repo so I'm taking a leap of faith and hope nothing broke in the process...
I noticed in the README it says this is "optional" advanced setup? How optional? Because the PR does says we **have to** `npm install` after this right?

**Comment by aedwardg** [comment]
Everyone will need to `npm install` after this and the pre-commit hook will be automatically set up for them.

The rest of the steps in Advanced Setup are optional -- though I personally like getting it all set up with my editor as well, so that I can see the linting while I type and have it format when I save, rather than waiting until I try to commit.

**Review by Vic-ST — APPROVED** [review]
Love it. LGTM!

**Review by selectlearns — COMMENTED** [review]
For JavaScript, I prefer the use of single-quotes instead of double-quotes.  All the examples in the Google JavaScript Style Guide also is done with single-quotes.

I'll go with whatever you guys agree on, of course. Just wanted to point this out before it goes live in case it was an oversight.

**Comment by fedGL** [comment]
To tell you the truth I use single quotes all the time, but same. I'm going with what the "pros" do

**Comment by aedwardg** [comment]
@selectlearns, @fedGL 

I use single quotes all the time as well, but a lot of code formatters (such as Black for Python and Prettier for JS) use double quotes to avoid excessive need for escaping.  You can find Prettier's rationale for defaulting to double quotes here: https://prettier.io/docs/en/rationale.html#strings

Prettier _does_ have an option to use single quotes instead (https://prettier.io/docs/en/options.html#quotes) and I'm fine with enabling that, but I'll need to reformat the whole repo again and push the changes.  It should be pretty straightforward. If we go with single quotes though, we'll have to do what Google does and use template strings ( `` ) wherever there's an apostrophe or else we'll end up with ugly escaping: `'and that\'s just sad'`

**Comment by fedGL** [comment]
People that need to escape a single ' simply aren't used to JS's template literals. I use them even more often than I use single quotes

**Review by Victoria-DR — APPROVED** [review]
Looks great, thanks @aedwardg!

**Comment by selectlearns** [comment]
Everything I'm about to write can be quickly tested in Codesandbox.io since they use Prettier and allow for the setting to be changed from double to single.  Feel free to verify using File > Settings > CodeSandbox Settings... > Prettier Settings > Use Single Quotes toggle.

The default for Prettier is to use whichever results in fewer escapes on a case by case basis. There's a "default default" (made up technical term that I just coined), that lets you set which to use when either would result in the same number of escapes.  That's why single is still useful, in my opinion.

Here are some examples.

Before Prettier reformat:
```javascript
const test1 = 'This\'ll show \'em';
const test2 = 'and then he said, "let there be quotes"';
const test3 = 'Hey, I just met you';
const test4 = "and this is crazy";
const test5 = "but here's my quote";
const test6 = "so escape me maybe";
```

Prettier reformat with double-quote option:
```javascript
const test1 = "This'll show 'em";
const test2 = 'and then he said, "let there be quotes"';
const test3 = "Hey, I just met you";
const test4 = "and this is crazy";
const test5 = "but here's my quote";
const test6 = "so escape me maybe";
```

Prettier reformat with single-quote options:
```javascript
const test1 = "This'll show 'em";
const test2 = 'and then he said, "let there be quotes"';
const test3 = 'Hey, I just met you';
const test4 = 'and this is crazy';
const test5 = "but here's my quote";
const test6 = 'so escape me maybe';
```

Notice that regardless of the setting chosen, it used whichever used the least number of escapes.  So when someone needs to use a `'` in a string, they can still use `"isn't"` and Prettier will accept it.  Or they could escape it with `'isn\'t'` and Prettier will change it to `"isn't"` even with the single-quote option enabled.

**Pull request merged**
