### PR TITLE
Updated cc!help command

### PR DESCRIPTION
**Pull request by Shaylin-TRK**
Now includes info for ping and stats commands. Now you can also get information about individual commands by typing their name after any of the help commands.

### CODE REVIEW

**Review by Vic-ST — APPROVED** [review]
LGTM!

**Review by fedGL — CHANGES_REQUESTED** [review]
I think the command handler already parses command and args? So to keep it consistent with the others, it would be best if we pass args to this call rather than having it parse args again inside of it

**Review by aedwardg — COMMENTED** [review]
I agree with @fedGL, if you look over at `app.js`, the arguments are already parsed out into a list inside of the `commandParser` function.  Rather than do that again here, it's probably better to just pass the args list to the help command's `execute` function rather than the whole message.

Other than that, this looks good and it's a nice little added functionality 👍

**Comment by Shaylin-TRK** [comment]
Done. The help function now has the `args` list passed to it from `commandParser`

**Review by fedGL — APPROVED** [review]
Awesome!

**Review by aedwardg — APPROVED** [review]
LGTM!

**Pull request merged**
