### PR TITLE
Update help command

### LINKED ISSUE #90: Update cc!help to include new commands
## Purpose
Since the last update of cc!help, the following commands have been added.
- cc!ban
- cc!unban
- cc!tempban
- cc!kick
- cc!mute
- cc!unmute
- cc!tempmute
- cc!warn
- cc!infractions

## Acceptance Criteria
- [x] The above commands and their descriptions are printed when `cc!help [command]` is used.
- [x] The descriptions for each command are based on the descriptions in [README.md](https://github.com/CodecademyCommunity/codecademy-discord-bot/blob/dev/README.md). _Note: there is currently a PR open that will change our README file._
- [x] If all the commands are to be printed (meaning no arguments are passed to cc!help), the commands are divided into sections based on who can use them.
- [x] If one of the above commands is provided as an argument to cc!help, only that command's information will be printed.

### PR DESCRIPTION
**Pull request by Victoria-DR**
Closes #90.

## Description
Edited cc!help to include new commands since it was last updated. `cc!help` now sends a MessageEmbed of the commands (sectioned by role access) rather than all the commands and descriptions. This is because we now have too many commands to be able to effectively list them all. Using `cc!help [command]` will still provide the user with the description specific to that command.

Side note: I also updated cc!tempmute to allow SUs to use it (this was an oversight when I initially wrote the command).

- [x] Code has been tested and does not produce errors.
- [x] Code is readable and formatted.
- [x] There isn't any unnecessary commented-out code.

### CODE REVIEW

**Review by Shaylin-TRK — CHANGES_REQUESTED** [review]
Only thing that seems slightly off is line 58 of help.js:
```
msg.channel.send('`cc!unban [userid]`\nUnbans a user. *Admin only.*');
```
To keep this similar to the rest it might be good to split into three lines:
```
msg.channel.send(
  '`cc!unban [userid]`\nUnbans a user. *Admin only.*'
);
```

Other than that, looks good to me!

**Review by Vic-ST — APPROVED** [review]
Other then Shaylin's point, LGTM!

**Review by Shaylin-TRK — APPROVED** [review]
LGTM!

**Review by aedwardg — APPROVED** [review]
This looks great @Victoria-DR 👍 

Just a heads up though, we should definitely avoid using `git commit --no-verify` when pushing changes to GitHub.  That's how bugs and sloppy code accidentally sneak back in.  In my other organization we even have the linting/formatting checked in the CI pipeline so if you try to circumvent it locally, your PR will fail the CI check and can't be merged 😂

Prettier will automatically truncate function calls to 1 line if that line is 80 chars long or under, which is sometimes totally fine, and sometimes quite annoying.  If for some reason we are _really_ opposed to something Prettier does, we can always put the following comment above the line or block that we don't want formatted:

```javascript
// prettier-ignore
```
You can see an example of that over in [constants.js](https://github.com/CodecademyCommunity/codecademy-discord-bot/blob/dev/constants.js) where I used it to prevent prettier from making the colors array have one color on each line.

But, in general I don't think it's worth adding a separate comment to our code just to enforce our own formatting of a single line.

**Pull request merged**
