### PR TITLE
Deleted Git workflow, moved to wiki

### LINKED ISSUE #23: Make project wiki or Google doc
**Purpose**

We may want to consider having a project wiki or Google doc to reference any important discussion points, etc. that might get lost on Discord.  See [this discussion](https://discord.com/channels/605859344243884081/810011899550892032/810323128969461762) for reference.

**Additional Information**

If we decide to go with a wiki, this issue will need to wait until the GitHub organization is in place and this repo is transferred over.

**Criteria**

- [ ] Come up with a way to document non-trivial group discussions for those who can't keep up with Discord on a daily basis.
- [ ] Make it both creative and organized

### PR DESCRIPTION
**Pull request by fedGL**
Now that we have a wiki, I thought it would be better to move some of the more basic information off CONTRIBUTING.md
I left the section with a little blurb telling people to go to the wiki if they need help. closes #23

### CODE REVIEW

**Review by Vic-ST — APPROVED** [review]
LGTM! Hopefully, this'll reduce some of the clutter on this file

**Review by Victoria-DR — APPROVED** [review]

**Review by Victoria-DR — CHANGES_REQUESTED** [review]
I think Clean Up should deleted as well (it's already in the wiki).

**Review by Victoria-DR — APPROVED** [review]
LGTM, thanks @fedGL!

**Comment by Victoria-DR** [comment]
@fedGL, for future merges, I think @Vic-ST wants to do the merges himself so because he needs to replicate it to **master** as well.

**Pull request merged**
