### PR TITLE
Only allow infractions belonging to the specified user to be removed

### LINKED ISSUE #132: Infractions with incorrect IDs can be removed
## Describe The Bug
`cc!removeinfraction` takes two arguments: `user` and `infractionid`. When the argument provided for `infractionid` is an infraction that exists and is valid but does not belong to the specified user, the infraction is removed (set to invalid).

## Expected Behavior
The infraction should not be removed and the moderator that used the command should be informed that the infraction ID specified does not belong to the user specified.

## To Reproduce
1. Try running `cc!removeinfraction [user] [id]` where `user` is a mention or user ID and `id` is the ID of an infraction that belongs to another user. 
2. The infraction will be set to invalid and removed.

## Additional Context
There is a similar fix for this already implemented in the `cc!removenote` command.

### PR DESCRIPTION
**Pull request by Victoria-DR**
## What issue is this solving?

Closes #132 

### Description

Changed the `validateInfractionID()` function to prevent the removal of infractions from unspecified users. Now, the infraction will be removed only if it belongs to the specified user. Nearly identical to what is already implemented in `cc!removenote`.

## Any helpful knowledge/context for the reviewer?

- Is a re-seeding of the database necessary? Need one infraction to test.
- Any new dependencies to install? NO
- Any special requirements to test? Usual perms to be able to use `cc!removeinfraction`.
  - (e.g., admin perms, alt account, etc.)

### Please make sure you've attempted to meet the following coding standards
- [x] Code has been tested and does not produce errors
- [x] Code is readable and formatted
- [x] There isn't any unnecessary commented-out code

### CODE REVIEW

**Review by aedwardg — COMMENTED** [review]
@Victoria-DR, 

This looks good.  The only thing I'd change is making the new message more informative, like it is in `removenote`.  Something like "The specified infraction does not belong to that user.:

**Comment by Victoria-DR** [comment]
> @Victoria-DR,
> 
> This looks good. The only thing I'd change is making the new message more informative, like it is in `removenote`. Something like "The specified infraction does not belong to that user.:

Done

**Review by aedwardg — APPROVED** [review]
Thanks, LGTM!

**Review by Vic-ST — APPROVED** [review]
Nice, got the notif, LGTM! Merging!

**Pull request merged**
