### PR TITLE
Add length checker

### LINKED ISSUE #140: Notify user when [reason] is too long
## Purpose
To inform admin/mod/su that their reason is too long _before_ executing the command instead of executing the command and failing to write to the DB.

### Is your feature request related to a problem? Please describe.
I tried to warn someone and the warn was successful, but it's not saved in the DB because it was 280 chars long.  I would have shortened it if I realized before the fact. 

## Proposed Solution
Check the length on fields that have a max char length _before_ executing the command, fail and warn the user if char length is too high.

## Acceptance Criteria
Please list the requirements the implementation of this feature should meet.
- [ ] Feature clearly warns user that their message is too long and returns without executing command
- [ ] Code is formatted, linted and does not contain unnecessary comments.

### PR DESCRIPTION
**Pull request by aedwardg**
## What issue is this solving?

Closes #140 

### Description

Adds functionality to the ban, tempban, kick, warn, mute and tempmute commands to notify server staff when the reason they provided is too long to be written into the database.

Prior to this, if your provided reason was too long, the command executed successfully, but failed to write to the db, rendering it useless for us when we need to go back and check infractions.

_Note that I also refactored the command collector here because I was considering collecting everything in the new `helpers` dir into a new Discord collection like we do with commands.  It ended up being easier to just import the function, but I'm leaving this refactor in here because it will make our lives easier going forward if we want to add another collector._ 

## Any helpful knowledge/context for the reviewer?

- Is a re-seeding of the database necessary? NO
- Any new dependencies to install? NO
- Any special requirements to test? YES
1. Test all 6 commands above with two reasons: one that is over the limit, one that is under.
2. NOTE: we can't provide reasons that are 255 chars for any of these because we are writing the entire msg.content into the `mod_logs` table. So if you are trying to manually measure for 255, you need to measure your whole message text and not just the provided reason.

### Please make sure you've attempted to meet the following coding standards
- [ ] Code has been tested and does not produce errors
- [ ] Code is readable and formatted
- [ ] There isn't any unnecessary commented-out code

### CODE REVIEW

**Comment by Vic-ST** [comment]
Hey, thanks for this, should help a lot.

One thing to note, when I try to ban users with too long of a reason I get this error:
442367989359181834

**Comment by aedwardg** [comment]
Hmm...let me check that out. The first one seems unrelated to this though, because it has to do with the filter.js file...

**Comment by Vic-ST** [comment]
You're right, looks like it was a problem with my cache or something, but I think the second one is still valid.

**Comment by aedwardg** [comment]
Alright, so I took a look into this and while I still think it has to do with the ban/kick sometimes happening _before_ the DM (see #145), I think there is also a way that we can circumvent this problem by properly fetching the user from the command.

The way we are doing it right now in `ban.js`, `tempban.js` and `kick.js` is like this:
https://github.com/CodecademyCommunity/codecademy-discord-bot/blob/0b0702e3e6ecde48cdbe2907dd9f06d1776744ed/commands/moderation/ban.js#L38-L39

Both sides of that conditional are susceptible to failure due to the person no longer being in the server.
`msg.mentions.members.first()` returns a `GuildMember` object from the mention, but as soon as the user is kicked/banned, they are no longer considered a guild member, so we can't use that object at all.

On the other side of that `||`, we see `msg.guild.members.cache.get(args[0])` to grab the user.
This is likewise susceptible to intermittent failure, because the `GuildMemberManager` cache stores `GuildMember` objects rather than `User` objects. So again, if the DM gets sent after the user is banned/kicked, it won't work.

Instead of this conditional, what we should be using is this:
```javascript
msg.mentions.users.first() || msg.client.users.fetch(args[0])
```
The first will return a `User` object from the mention, and the latter is what we're using in `unban.js` in order to message someone who has already been banned.

I think this should solve this issue without adding any `async` to the mix, though we should probably still implement the `async` functionality into our code in case _other_ errors come up.

**Comment by aedwardg** [comment]
Actually, it looks like the `GuildMember` is needed for the kick and ban actions, but the `User` is needed for DMing after the ban/kick and for unbanning.  This will be an easy fix and will actually be less intrusive than my proposed solution above. 👍

**Comment by aedwardg** [comment]
EDIT: nevermind, it looks like we still need the GuildMember object, because we can't send messages to a user without it. It looks like fixing the async problem may be the only real fix. Anyway, I'll come back to this after lunch and hopefully figure it all out then.

**Comment by aedwardg** [comment]
Marking this one as on hold until #172 is merged into dev so I can rebase this and make sure everything still works.

**Review by Victoria-DR — APPROVED** [review]
Looks great, thanks! 🚀

**Review by Vic-ST — APPROVED** [review]
LGTM!

**Pull request merged**
