### PR TITLE
convert verbal command to slash cmd

### LINKED ISSUE #300: Convert verbal to slash command

### PR DESCRIPTION
**Pull request by mikejoh12**
## What issue is this solving?

Closes #300

### Description

Converts cc!verbal to a slash command.

## Any helpful knowledge/context for the reviewer?

- Is a re-seeding of the database necessary? No
- Any new dependencies to install? No
- Any special requirements to test? Send a verbal to test account.
  - (e.g., admin perms, alt account, etc.)

### Please make sure you've attempted to meet the following coding standards
- [X] Code has been tested and does not produce errors
- [X] Code is readable and formatted
- [X] There isn't any unnecessary commented-out code

### CODE REVIEW

**Review by Victoria-DR — APPROVED** [review]
LGTM!

**Review by lyallstewart — APPROVED** [review]
🔥

**Comment by mikejoh12** [comment]
I added error handling for users with DMs disabled. In case of blocked DMs on the target-user the command will now inform the person using the command that DMs are likely blocked so that they can take other action.

Also incorporated the helper function to verify that reason length fits in the database column. Since some text was added to the reason in one of the tables, I needed to use a value less than 255 characters. The verifyReasonLength function was slightly modified to display the correct max length in case of values other than 255.

**Review by aedwardg — APPROVED** [review]
Looks good!

**Review by Victoria-DR — APPROVED** [review]

**Review by lyallstewart — APPROVED** [review]
LGTM! There appears to be a conflict but once that's resolved I'd say good to merge 😄

**Pull request merged**
