### PR TITLE
Update helpcenter.js

### PR DESCRIPTION
**Pull request by fedGL**
Updates to the command to comply with new guidance from Codecademy Customer Support Team

## What issue is this solving?

Closes #???

## Any helpful knowledge/context for the reviewer?

- Is a re-seeding of the database necessary?
- Any new dependencies to install?
- Any special requirements to test?
  - (e.g., admin perms, alt account, etc.)

### Please make sure you've attempted to meet the following coding standards
- [ ] Code has been tested and does not produce errors
- [ ] Code is readable and formatted
- [ ] There isn't any unnecessary commented-out code

### CODE REVIEW

**Review by lyallstewart — APPROVED** [review]
Looks good to me!

Just curious, if the "requests" page is being phased out what is the intended way of contacting CC and where should we direct users to?

**Comment by fedGL** [comment]
@lyallstewart this update removes the link for users to directly submit requests. Customer support team said they need users to go through the normal support flow (landing in help.codecademy.com first)

**Comment by lyallstewart** [comment]
Makes sense, thanks!

In that case might be best to remove the "All billing-related queries should be directed to the Submit A Request form linked above." message from the bottom of the embed too, seeing as the form it refernces isn't linked there anymore.

**Comment by fedGL** [comment]
good catch, changed the language

**Review by Vic-ST — APPROVED** [review]
LGTM!

**Pull request merged**
