### PR TITLE
Add async-await to ban, kick & tempban

### LINKED ISSUE #145: Ban and Kick commands should be async to ensure DM delivery
## Describe the bug
Ban and Kick commands are sometimes unable to DM the user because the user is booted from the server before the message has completed sending.  

## Expected behavior
The ban/kick should not execute until the messaging has occurred.  

This will need to have some error handling in case the user has DMs off, but basically the bot should attempt the DM and should not begin the ban/kick until the message promise resolves or is rejected (e.g., if the user has DMs turned off for the server).  This issue might be best to save until #136 has been completed, so that disabled DMs are all handled the same way.

## To Reproduce
Steps to reproduce the behavior: NOTE: this might only happen when your internet connection is slow.
1. Try to ban/kick your alt
2. Check to see if your alt got a DM.
4. If not, see error.

### Screenshots
This is the error I got, even though my alt's DMs were enabled:
image

### PR DESCRIPTION
**Pull request by aedwardg**
## What issue is this solving?

Closes #145 

### Description

Uses async/await to ensure actions are taken in the proper order for the ban, kick and tempban commands.

## Any helpful knowledge/context for the reviewer?

- Is a re-seeding of the database necessary? NO
- Any new dependencies to install? NO
- Any special requirements to test? NO
  - (e.g., admin perms, alt account, etc.)

### Please make sure you've attempted to meet the following coding standards
- [ ] Code has been tested and does not produce errors
- [ ] Code is readable and formatted
- [ ] There isn't any unnecessary commented-out code

### CODE REVIEW

**Comment by aedwardg** [comment]
Note: for some reason the unban DM in tempban works when I test on our dev server, but not when testing in my personal server.  I have no idea why, since all the settings seem to be the same.  

However, we are probably getting rid of that DM -- or even the whole `tempban` command in the near future, so it's not a big deal.  See [this discussion](https://discord.com/channels/810930683732033597/810930684171780117/854411395118137441) for details

**Review by Victoria-DR — APPROVED** [review]
LGTM

**Review by Vic-ST — APPROVED** [review]
Alright LGTM!

**Comment by aedwardg** [comment]
Merging this to `dev`, hope to have #170 rebased and ready for final review soon.

**Pull request merged**
