### PR TITLE
Add MySQL db recreate script

### LINKED ISSUE #15: Create Database Creation Tool
Write a file which, when run, creates all the tables in the database that are needed for the project. Right now, we only have one, `verifications`, but this issue will be edited as more tables are created in the project.

- [ ] Verifications table
   - `CREATE TABLE verifications(username varchar(255), id varchar(255) NOT NULL, expiration varchar(255));`
 - [ ] Infractions tabe
   - `CREATE TABLE infractions( id INT AUTO_INCREMENT PRIMARY KEY, timestamp varchar(255), user varchar(255) NOT NULL, action varchar(255), lengthOfTime varchar(255), reason varchar(255), invalid boolean, moderator varchar(255) );`

### PR DESCRIPTION
**Pull request by aedwardg**
### What issue is this solving?
Closes #15 

You can wipe the MySQL database and re-create all tables from scratch.
To use this new script, run the following command:
```bash
$ npm run db-recreate 
```

### Changes
- Adds new script to drop and recreate all current tables in the db.
  - This is mostly for dev/testing purposes and getting new contributors
    up and running.
- Adds new script command and `dateformat` dependency in `package.json`
- Uses new MySQL datetime format in `sendcode.js`

This script is for MySQL, but we may change over to Mongo in the future.

Whichever database we choose, it may be wise to switch over to an ORM
for database interaction. For MySQL, we could use [Sequelize](https://sequelize.org/master/index.html), for Mongo
we could use [Mongoose](https://mongoosejs.com/).

---

### Additional Information
- Any new dependencies to install (`npm install`)? YES
- Any special requirements to test? YES
  - Install the new deps
  - You need to have `DB_USER`, `DB_HOST`, `DB_DATABASE` and `DB_PASSWORD` for a MySQL db in your `.env` file
  - Your DB User must have perms to drop and create tables

### CODE REVIEW

**Review by Vic-ST — CHANGES_REQUESTED** [review]
Looks amazing thanks so much for this

One small thing - can you change the invalid on the infractions table to valid?

**Comment by aedwardg** [comment]
> 
> One small thing - can you change the invalid on the infractions table to valid?

Done, sorry about that! Got sidetracked looking up ORMs for Node and forgot to change that one!

**Review by Vic-ST — APPROVED** [review]
LGTM! Thanks for this!

**Review by Victoria-DR — APPROVED** [review]
LGTM! 🚀

**Review by fedGL — APPROVED** [review]

**Pull request merged**
